{
 "title": "Energy Metrics",
 "time": { "from": "now-48h", "to": "now+24h" },
 "panels": [
  {
   "title": "Live Energy Prices",
   "type": "timeseries",
   "description": "Live Zonneplan Energy Prices",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "import \"math\"\nfrom(bucket: \"zonneplan\")\n  |> range(start: now(), stop: 24h)\n  |> filter(fn: (r) => r._measurement == \"price_per_hour\")\n  |> filter(fn: (r) => r._field == \"electricity_price\")\n  |> map(fn: (r) => ({ r with _value: float(v: math.round(x: float(v: r._value))) / 100.0 }))"
    },
    {
     "query": "import \"math\"\n\nfrom(bucket: \"zonneplan\")\n  |> range(start: -24h, stop: now())\n  |> filter(fn: (r) => r._measurement == \"price_per_hour\" and r._field == \"electricity_price\")\n  |> map(fn: (r) => ({\n      r with \n      _value: float(v: math.round(x: float(v: r._value))) / 100.0,\n      tariff_group: if r.tariff_group == \"high\" then \"high_old\"\n                    else if r.tariff_group == \"normal\" then \"normal_old\"\n                    else if r.tariff_group == \"low\" then \"low_old\"\n                    else r.tariff_group\n    }))\n"
    }
   ]
  },
  {
   "title": "Electricity Price Over Time",
   "type": "timeseries",
   "description": "Displaying the electricity price over time for each tariff group.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"zonneplan\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"price_per_hour\")\n    |> filter(fn: (r) => r[\"_field\"] == \"electricity_price\")\n    |> filter(fn: (r) => r[\"tariff_group\"] == \"high\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"zonneplan\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"price_per_hour\")\n    |> filter(fn: (r) => r[\"_field\"] == \"electricity_price\")\n    |> filter(fn: (r) => r[\"tariff_group\"] == \"normal\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"zonneplan\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"price_per_hour\")\n    |> filter(fn: (r) => r[\"_field\"] == \"electricity_price\")\n    |> filter(fn: (r) => r[\"tariff_group\"] == \"low\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Sustainability Score",
   "type": "gauge",
   "description": "This visualization offers a quick, easy-to-understand graphical representation of the percentage of sustainable energy at any given point in time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"zonneplan\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"price_per_hour\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sustainability_score\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Comparison of Electricity Price and Sustainability Score",
   "type": "timeseries",
   "description": "Plots both the electricity price and the sustainability score over time. This could provide insights into whether higher sustainability scores correlate with higher or lower electricity prices.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"zonneplan\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"price_per_hour\")\n    |> filter(fn: (r) => r[\"_field\"] == \"electricity_price\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"zonneplan\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"price_per_hour\")\n    |> filter(fn: (r) => r[\"_field\"] == \"sustainability_score\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Database Error Log",
   "type": "logs",
   "description": "Errors on Price Database",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"zonneplan_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"error\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Database Errors",
   "type": "timeseries",
   "description": "Errors on Price Database",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"zonneplan_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"error\")\n  |> group(columns: [\"type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Database Operations",
   "type": "timeseries",
   "description": "Write Operations on Price Database",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "query": "import \"math\"\nfrom(bucket: \"zonneplan_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"write\")"
    }
   ]
  }
 ]
}